# theme: hackerman-float
background              #0B0C16
foreground              #DDF7FF
cursor                  #DDF7FF
cursor_text_color       #0B0C16
selection_foreground    #DDF7FF
selection_background    #82FB9C
active_tab_background   #141722
active_tab_foreground   #82FB9C
inactive_tab_background #1A1D29
inactive_tab_foreground #788B92

color0  #0B0C16
color1  #FF6B7A
color2  #82FB9C
color3  #E5D57A
color4  #77C7FF
color5  #B8A1FF
color6  #7BE7E7
color7  #DDF7FF
color8  #56656B
color9  #FF8793
color10 #9DFFB2
color11 #F4E68E
color12 #9AD7FF
color13 #CDBBFF
color14 #9AF4F4
color15 #FFFFFF

background_opacity 0.90
