background = 0xFF0B0C16
base = 0xFF141722
text = 0xFFDDF7FF
alternate_base = 0xFF1A1D29
bright_text = 0xFF82FB9C
accent = 0xFF82FB9C
link_text = 0xFF82FB9C
accent_secondary = 0xFF9DFFB2
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 8
rounding_small = 4
